#[macro_export]
macro_rules! kand_indicator {
    (
        $name:ident,
        inputs: { $($input_name:ident : $input_type:ty),+ },
        params: { $($param_name:ident : $param_type:ty),* },
        state: { $($state_field:ident : $state_type:ty),* },
        init: |$init_params:ident| $init_block:block,
        next: |$next_state:ident, $next_input:ident| $next_block:block
    ) => {
        $crate::paste::paste! {
            /// Stateful implementation generated by macro.
            #[derive(Clone)]
            pub struct [<Stateful $name:upper>] {
                $($param_name : $param_type,)*
                $($state_field : $state_type,)*
                __kand_count: usize,
            }

            impl [<Stateful $name:upper>] {
                /// Creates a new stateful instance.
                pub fn new($($param_name : $param_type),*) -> Result<Self, $crate::KandError> {
                    let $init_params = ($($param_name),*);
                    let state = $init_block;
                    Ok(Self {
                        $($param_name,)*
                        $($state_field : state,)* // Simplification for now: assumes init returns a single value if only one state field
                        __kand_count: 0,
                    })
                }
            }
        }
    };
}
